// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW0bLHSUOSA2aUalx53_RNJ8nbzete1ME',
    appId: '1:594956975659:web:76fbc129d2b403c146346e',
    messagingSenderId: '594956975659',
    projectId: 'wantorest-v0-0-1',
    authDomain: 'wantorest-v0-0-1.firebaseapp.com',
    storageBucket: 'wantorest-v0-0-1.appspot.com',
    measurementId: 'G-E1PC78JT84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCMrjWmv_v2TMx1lIUuonUsxzJpO2wNKg',
    appId: '1:594956975659:android:1cf860ba86f41c2c46346e',
    messagingSenderId: '594956975659',
    projectId: 'wantorest-v0-0-1',
    storageBucket: 'wantorest-v0-0-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu2MZRe57P3OBQZYBngdG42HLTqSzL3oM',
    appId: '1:594956975659:ios:0e6622f92217d2f446346e',
    messagingSenderId: '594956975659',
    projectId: 'wantorest-v0-0-1',
    storageBucket: 'wantorest-v0-0-1.appspot.com',
    iosBundleId: 'com.example.wantorestaurantApp',
  );

}